name: Add Lable after approval

on:
  pull_request_review:
    branches: [ $default ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Label when approved
        uses: pullreminders/labale-when-approved-action@main
        env:
          APPROVALS: "1"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ADD_LABEL: "approved"
